# Background and foreground colors
background = #121212
foreground = #ffffff

# Standard colors
palette = 0=#121212
palette = 1=#e39a82
palette = 2=#769b4b
palette = 3=#8a9b4b
palette = 4=#7675d2
palette = 5=#8b75d2
palette = 6=#759b4b
palette = 7=#ffffff

# Bright colors
palette = 8=#9e9e9e
palette = 9=#eda892
palette = 10=#8bbb54
palette = 11=#a5bb54
palette = 12=#9b95ff
palette = 13=#b294ff
palette = 14=#8abb54
palette = 15=#ffffff
